version: "3.9"
services:
  go-mongodb-app:
    build: .
    networks:
      - db_network
    depends_on:
      - mongodb
    ports:
      - "8080:80"
  mongodb:
    image: mongo:5.0.6
    volumes:
      - mongo-vol:/var/lib/docker/
    ports:
      - "27017:27017"
    networks:
      - db_network
volumes:
  mongo-vol:
networks:
  db_network:  